name: CI
on: [push]

jobs:
  lint & tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn
        
      - name: Run ESLint
        run: yarn lint

      - name: Run Vitest
        run: yarn test